import { ArrayFn1 } from "./array/ex1";
import { ArrayFn2 } from "./array/ex2";
import { ArrayFn3 } from "./array/ex3";
import { ArrayFn4 } from "./array/ex4";
import { ArrayFn5 } from "./array/ex5";
import { ArrayFn6 } from "./array/ex6";
import { ArrayFn7 } from "./array/ex7";
import { ArrayFn8 } from "./array/ex8";
import { ArrayFn9 } from "./array/ex9";
import { ArrayFn10 } from "./array/ex10";
import { ArrayFn20 } from "./array/ex20";
import { ArrayFn21 } from "./array/ex21";
import { ArrayFn22 } from "./array/ex22";
import { ArrayFn23 } from "./array/ex23";
import { ArrayFn24 } from "./array/ex24";
import { ArrayFn25 } from "./array/ex25";
import { ArrayFn26 } from "./array/ex26";
import { ArrayFn27 } from "./array/ex27";
import { ArrayFn28 } from "./array/ex28";
import { ArrayFn29 } from "./array/ex29";
import { ArrayFn30 } from "./array/ex30";
import { DictFn1 } from "./dict/ex1";
import { DictFn2 } from "./dict/ex2";
import { DictFn3 } from "./dict/ex3";
import { DictFn4 } from "./dict/ex4";
import { DictFn5 } from "./dict/ex5";
import { DictFn6 } from "./dict/ex6";
import { DictFn7 } from "./dict/ex7";
import { functionFn1 } from "./function/ex1";
import { functionFn2 } from "./function/ex2";
import { functionFn3 } from "./function/ex3";
import { functionFn4 } from "./function/ex4";

console.log('Exécution des exercices de ARRAY :');
console.log('Exécution de l\'exercice 1 :');
ArrayFn1();
console.log('Exécution de l\'exercice 2 :');
ArrayFn2();
console.log('Exécution de l\'exercice 3 :');
ArrayFn3();
console.log('Exécution de l\'exercice 4 :');
ArrayFn4();
console.log('Exécution de l\'exercice 5 :');
ArrayFn5();
console.log('Exécution de l\'exercice 6 :');
ArrayFn6();
console.log('Exécution de l\'exercice 7 :');
ArrayFn7();
console.log('Exécution de l\'exercice 8 :');
ArrayFn8();
console.log('Exécution de l\'exercice 9 :');
ArrayFn9();
console.log('Exécution de l\'exercice 10 :');
ArrayFn10();
console.log('Exécution de l\'exercice 20 :');
ArrayFn20();
console.log('Exécution de l\'exercice 21 :');
ArrayFn21();
console.log('Exécution de l\'exercice 22 :');
ArrayFn22();
console.log('Exécution de l\'exercice 23 :');
ArrayFn23();
console.log('Exécution de l\'exercice 24 :');
ArrayFn24();
console.log('Exécution de l\'exercice 25 :');
ArrayFn25();
console.log('Exécution de l\'exercice 26 :');
ArrayFn26();
console.log('Exécution de l\'exercice 27 :');
ArrayFn27();
console.log('Exécution de l\'exercice 28 :');
ArrayFn28();
console.log('Exécution de l\'exercice 29 :');
ArrayFn29();
console.log('Exécution de l\'exercice 30 :');
ArrayFn30();

console.log('Exécution des exercices de Dict :');
console.log('Exécution de l\'exercice 1 :');
DictFn1();
console.log('Exécution de l\'exercice 2 :');
DictFn2();
console.log('Exécution de l\'exercice 3 :');
DictFn3();
console.log('Exécution de l\'exercice 4 :');
DictFn4();
console.log('Exécution de l\'exercice 5 :');
DictFn5();
console.log('Exécution de l\'exercice 6 :');
DictFn6();
console.log('Exécution de l\'exercice 7 :');
DictFn7();

console.log('Exécution des exercices de Functions :');
console.log('Exécution de l\'exercice 1 :');
functionFn1();
console.log('Exécution de l\'exercice 2 :');
functionFn2();
console.log('Exécution de l\'exercice 3 :');
functionFn3();
console.log('Exécution de l\'exercice 4 :');
functionFn4();